version: 0.1

phases:
  build:
    commands:
      - npm install
      - npm run webpack
artifacts:
  files:
    - index.html
    - favicon.icon
    - README.md
    - images/**
    - styles/**
    - dist/bundle.js
